### ISSUE TITLE
CocoaPods

### ISSUE THREAD

**Issue by lfarah** [jakelawson1/FlickToDismiss#2]
I'd be cool to also add Cocoapods support. I done this implementation myself last month for my library. Just follow [this post](https://guides.cocoapods.org/making/making-a-cocoapod.html) and [this checklist](https://github.com/thellimist/EZPods).

**Comment by jakelawson1** [comment]
Thanks for the suggestion. I've just added CocoaPods support.

**Comment by lfarah** [comment]
Wow you're fast! 🚀🚀
